#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Token Punk Records — one-command setup & run
#
#   ./run.sh          Set up (if needed) and start BOTH servers.
#   ./run.sh setup    Only install dependencies, don't start servers.
#
# Rebuilds the excluded folders from lockfiles:
#   backend/.venv          <- backend/requirements.txt
#   frontend/node_modules  <- frontend/package-lock.json
#   frontend/.next         <- generated by `npm run dev`
#
# You MUST create .env first (copy .env.example and fill in AWS keys).
# ---------------------------------------------------------------------------
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

# --- 0. Check .env exists -------------------------------------------------
if [[ ! -f .env ]]; then
  echo "❌ No .env found."
  echo "   Create it first:  cp .env.example .env  (then fill in your AWS keys)"
  exit 1
fi

# --- 1. Backend venv + deps ----------------------------------------------
echo "▶ Setting up backend…"
cd "$ROOT/backend"
if [[ ! -d .venv ]]; then
  echo "  creating virtualenv…"
  python3 -m venv .venv
fi
# shellcheck disable=SC1091
source .venv/bin/activate
pip install -q --upgrade pip
pip install -q -r requirements.txt
deactivate
echo "  backend ready."

# --- 2. Frontend deps -----------------------------------------------------
echo "▶ Setting up frontend…"
cd "$ROOT/frontend"
if [[ ! -d node_modules ]]; then
  npm install
else
  echo "  node_modules present (run 'npm install' manually to refresh)."
fi
echo "  frontend ready."

# --- Stop here if only setting up ----------------------------------------
if [[ "${1:-}" == "setup" ]]; then
  echo "✅ Setup complete. Run ./run.sh to start the servers."
  exit 0
fi

# --- 3. Start both servers ------------------------------------------------
echo "▶ Starting servers…"
cd "$ROOT/backend"
# Load .env into the backend's environment
set -a
# shellcheck disable=SC1091
. "$ROOT/.env"
set +a
source .venv/bin/activate
uvicorn main:app --reload --port 8000 &
BACKEND_PID=$!

cd "$ROOT/frontend"
npm run dev &
FRONTEND_PID=$!

# Clean up both processes on Ctrl+C / exit
cleanup() {
  echo ""
  echo "▶ Shutting down…"
  kill "$BACKEND_PID" "$FRONTEND_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

echo ""
echo "✅ Running:"
echo "   Backend  → http://localhost:8000  (docs: /docs)"
echo "   Frontend → http://localhost:3000"
echo "   Press Ctrl+C to stop both."
echo ""

# Wait for either process to exit
wait
